export const GET_BOARDS = 'GET_BOARDS';
export const BOARDS_LOADING = 'BOARDS_LOADING';

export const CREATE_BOARD = 'CREATE_BOARD';
export const BOARD_CREATE_SUCCESS = 'BOARD_CREATE_SUCCESS';
export const BOARD_CREATE_FAIL =  'BOARD_CREATE_FAIL';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';